### ISSUE TITLE
[BUG] "no index mapper found for field" warning appears even if there is no knn-vector mapping

### ISSUE THREAD

**Issue by fiarabbit** [opensearch-project/k-NN#537]
**What is the bug?**
When multiple indices are configured with `settings.index.knn=true`, warning messages appears when `object` (or `nested`) type document  is created.

Oddly, the warning messages appear for the index where the document is NOT created .

When `settings.index.knn=false` is set, these warning messages do not appear.

This bug only appears for OpenSearch 1.x (I confirmed with 1.3.3 and 1.3.5), not for OpenSearch 2.x (checked 2.2.1).

**How can one reproduce the bug?**
1. run Docker
```bash
$ docker run -p 9200:9200 -p 9600:9600 -e "discovery.type=single-node"  opensearchproject/opensearch:1.3.5
```
2. execute the command below
(1) create index1 with knn index
(2) create index2 with knn index
(3) put a simple object doc to index1
```bash
$ curl --location --request PUT 'https://localhost:9200/index1' \
--header 'Content-Type: application/json' \
--data-raw '{
    "settings": {
        "index": {
            "knn": true
        }
    }
}' \
--user 'admin:admin' \
--insecure 

$ curl --location --request PUT 'https://localhost:9200/index2' \
--header 'Content-Type: application/json' \
--data-raw '{
    "settings": {
        "index": {
            "knn": true
        }
    }
}' \
--user 'admin:admin' \
--insecure 

$ curl --location --request PUT 'https://localhost:9200/index1/_doc/doc1' \
--header 'Content-Type: application/json' \
--data-raw '{
    "parent": {
        "child": "aaa"
    }
}' \
--user 'admin:admin' \
--insecure 
```
4. See warning
```
[2022-09-07T08:08:46,096][INFO ][o.o.c.m.MetadataCreateIndexService] [4acb15cf78d5] [index1] creating index, cause [api], templates [], shards [1]/[1]
[2022-09-07T08:08:46,122][INFO ][o.o.c.m.MetadataCreateIndexService] [4acb15cf78d5] [security-auditlog-2022.09.07] creating index, cause [auto(bulk api)], templates [], shards [1]/[1]
[2022-09-07T08:08:46,226][INFO ][o.o.c.m.MetadataMappingService] [4acb15cf78d5] [security-auditlog-2022.09.07/_M92EiDzTZ-wadZ6wQPWgg] create_mapping [_doc]
[2022-09-07T08:08:50,872][INFO ][o.o.c.m.MetadataCreateIndexService] [4acb15cf78d5] [index2] creating index, cause [api], templates [], shards [1]/[1]
[2022-09-07T08:08:55,360][INFO ][o.o.c.m.MetadataMappingService] [4acb15cf78d5] [index1/VHy9DleQRfCZcHA2-Cx12g] create_mapping [_doc]
[2022-09-07T08:08:55,396][INFO ][o.o.c.m.MetadataMappingService] [4acb15cf78d5] [security-auditlog-2022.09.07/_M92EiDzTZ-wadZ6wQPWgg] update_mapping [_doc]
[2022-09-07T08:08:56,189][WARN ][o.o.i.s.IndexShard       ] [4acb15cf78d5] [index2][0] no index mapper found for field: [_id] returning default postings format
[2022-09-07T08:08:56,189][WARN ][o.o.i.s.IndexShard       ] [4acb15cf78d5] [index2][0] no index mapper found for field: [parent.child] returning default postings format
[2022-09-07T08:08:56,189][WARN ][o.o.i.s.IndexShard       ] [4acb15cf78d5] [index2][0] no index mapper found for field: [parent.child.keyword] returning default postings format
```

**What is the expected behavior?**
No warning happens

**What is your host/environment?**
 - OS: Max OS X 12.5.1
 - Version: 1.3.5
 - Plugins: default plugins (including opensearch-knn)

**Comment by jmazanec15** [comment]
Hi @fiarabbit 

Taking a look into this.

**Comment by jmazanec15** [comment]
I see. I think this was fixed by #319, which went out in 2.0.

From a high level, there is a way to configure posting formats per field through the [PerFieldPostingsFormatCodec](https://github.com/opensearch-project/OpenSearch/blob/1.3/server/src/main/java/org/opensearch/index/codec/PerFieldMappingPostingFormatCodec.java#L74). This is where the warning is coming from. 

This will get created and registered in the [CodecService constructor](https://github.com/opensearch-project/OpenSearch/blob/1.3/server/src/main/java/org/opensearch/index/codec/CodecService.java#L66-L67).

For k-NN, we call this CodecService constructor here: https://github.com/opensearch-project/k-NN/blob/1.3/src/main/java/org/opensearch/knn/plugin/KNNCodecService.java#L19. MapperService should be null so the perfieldpostingformat should never get created. 

However, the default constructor for the CodecService is called before our KNNCodecService is called [here](https://github.com/opensearch-project/OpenSearch/blob/1.3/server/src/main/java/org/opensearch/index/codec/CodecService.java#L66-L67). Here the MappingService wont be null. As a hack, we get the per field posting format from the default codec and set it for our codec [here](https://github.com/opensearch-project/k-NN/blob/1.3/src/main/java/org/opensearch/knn/plugin/KNNEngineFactory.java#L22).

When we look at the mapperservice, however, because no mapping has been specified already, the mapper in the MapperService is null, resulting in this condition to be false in [PerFieldPostingsFormatCodec](https://github.com/opensearch-project/OpenSearch/blob/1.3/server/src/main/java/org/opensearch/index/codec/PerFieldMappingPostingFormatCodec.java#L74).

I believe if mapping if specified at index time, this error should not be reached in 1.3.

Aside from the warning, is this causing any error in your application?

**Comment by fiarabbit** [comment]
@jmazanec15 
Thanks for your polite reply!

> I believe if mapping if specified at index time, this error should not be reached in 1.3.
Actually, even if I specify the mapping at index time, this warning message still appears.

### code to reproduce
send sequentially the following requests.
```
PUT /index1
{
    "settings": {
        "index": {
            "knn": true
        }
    },
    "mappings": {
        "properties": {
            "parent1": {
                "type": "nested",
                "properties": {
                    "child1": {"type": "keyword"}
                }
            }
        }
    }
}

PUT /index2
{
    "settings": {
        "index": {
            "knn": true
        }
    },
    "mappings": {
        "properties": {
            "parent2": {
                "type": "nested",
                "properties": {
                    "child2": {"type": "keyword"}
                }
            }
        }
    }
}

PUT /index1/_doc/doc1
{
    "parent1": {
        "child1": "aaa"
    }
}
```
Log
```
[2022-09-16T05:38:31,949][INFO ][o.o.c.m.MetadataCreateIndexService] [fda10f447ef4] [index1] creating index, cause [api], templates [], shards [1]/[1]
[2022-09-16T05:38:36,981][INFO ][o.o.c.m.MetadataCreateIndexService] [fda10f447ef4] [index2] creating index, cause [api], templates [], shards [1]/[1]
[2022-09-16T05:38:43,130][WARN ][o.o.i.s.IndexShard       ] [fda10f447ef4] [index2][0] no index mapper found for field: [parent1.child1] returning default postings format
```

> Aside from the warning, is this causing any error in your application?
No, I haven't found any data inconsistency in our actual application.
I raised this ticket because I cannot judge this is an actual problem, or I can just ignore these messages.

**Comment by jmazanec15** [comment]
Got it. Yes this should not cause a problem from data consistency standpoint. It should be fixed in 2.x releases.
